### ISSUE TITLE
Wrong data?

### ISSUE THREAD

**Issue by cbrnr** [agramfort/mne_scipy2017#1]
I followed along with your notebook, but averaging over epochs gives strange results (I didn't change anything):

![screenshot from 2017-07-13 14-04-35](https://user-images.githubusercontent.com/4377312/28165499-53bd62f8-67d4-11e7-8812-0115ea245872.png)

Any idea what the problem could be?

**Comment by agramfort** [comment]
you seem to have a baseline problem that's weird

can you run this tutorial:

http://martinos.org/mne/dev/auto_examples/datasets/plot_spm_faces_dataset.html

?

**Comment by cbrnr** [comment]
The figs from this tutorial (the evoked plots) look identical to the ones on the website.

In your notebook, the data plot already looks slightly different.

![data](https://user-images.githubusercontent.com/4377312/28167038-6ade2502-67da-11e7-8cc4-c00dcbc2d476.png)

**Comment by agramfort** [comment]
hum but why did you see flat lines?

**Comment by cbrnr** [comment]
There are some weird channels in the data, e.g. 282, 283, 284, 289, 290, ...

Averaged over epochs, e.g. channel 290 looks like this:
![ch290](https://user-images.githubusercontent.com/4377312/28167907-94029654-67dd-11e7-8332-70f3e4120a36.png)

**Comment by agramfort** [comment]
ref_meg channels

are you using master?

**Comment by cbrnr** [comment]
Nope. OK, I guess we found the problem then :-). Maybe you could include the version string at the top of the notebook (I was getting suspicious when you used the `fir_design` argument in the `filter` function...).

**Comment by agramfort** [comment]
we should release...
